name: Deploy to Hostinger VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Deploy to Hostinger VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          set -e
          cd ${{ secrets.DEPLOYMENT_PATH }}
          git fetch origin main
          git reset --hard origin/main
          echo "Deployment completed at $(date)"